/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evemarginfinder;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author austin-z
 */
public class FilterFrame extends javax.swing.JFrame {
    
    private final List<FilterPanel> panels = new ArrayList<>();
    
    /**
     * Creates new form FilterFrame
     */
    public FilterFrame() {
        initComponents();
    }

    public void loadCfg(){
        Configuration.stream()
                .filter(e -> e.getKey().startsWith("filter-"))
                .forEach(e -> add(e.getKey().replace("filter-", ""), e.getValue()));
        
        filter.revalidate();
        
    }
    
    public String get(String key){
        for(FilterPanel panel : panels){
            if(panel.key().equals(key)){
                return panel.value();
            }
        }
        return null;
    }
    
    public boolean set(String key, String value){
        for(FilterPanel panel : panels){
            if(panel.key().equals(key)){
                panel.setVal(value);
                panel.repaint();
                return true;
            }
        }
        return false;
    }
    
    public void saveCfg(){
        panels.stream().forEach((p) -> {
            Configuration.set("filter-" + p.key(), p.value());
        });
    }
    
    public FilterPanel add(){
        return add("", "");
    }
    
    public FilterPanel add(String key, String value){
        FilterPanel p = new FilterPanel(this);
        
        p.sKey(key);
        p.setVal(value);
        
        
        panels.add(p);
        Component[] child = filter.getComponents();
        filter.add(p, child.length >= 2 ?  child.length - 2 : 0);
        
        filter.revalidate();
        filter.repaint();
        
        System.out.println(filter.getComponents().length);
        
        return p;
    }
    
    public boolean remove(FilterPanel p){
        boolean suc = panels.remove(p);
        filter.remove(p);
        
        filter.revalidate();
        filter.repaint();
        
        return suc;
    }
    
    public static void main(String[] args){
        SwingUtilities.invokeLater(()->{
            new FilterFrame().setVisible(true);
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        filter = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        add_filter = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(373, 300));
        setName("Filters"); // NOI18N

        filter.setLayout(new javax.swing.BoxLayout(filter, javax.swing.BoxLayout.PAGE_AXIS));
        filter.add(filler1);

        jScrollPane1.setViewportView(filter);

        add_filter.setText("Add");
        add_filter.setToolTipText("Add New Filter");
        add_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_filterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 331, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(add_filter)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_filter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_filterActionPerformed
        add();
    }//GEN-LAST:event_add_filterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_filter;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel filter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
